trigger:
  branches:
    include:
      - main
  paths:
    include:
      - Frontend/**

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '^18.18.0' # Specify the version of Node.js you are using
            displayName: 'Install Node.js'

          - script: |
              cd Frontend
              cd ReactDemo
              npm install
              npm run build --force
            displayName: 'Build React App'

          - task: CopyFiles@2
            inputs:
              contents: 'build/**'
              targetFolder: '$(Build.ArtifactStagingDirectory)'
              displayName: 'Copy Files to ArtifactStagingDirectory'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'react-graphql'
            displayName: 'Publish Artifact'
